"""
Config module exports - single source of truth for all strategy parameters
v2.1 - Updated with new signal generation and API optimization parameters
"""

from config.config import (
    # API Rate Limits
    API_RATE_LIMIT,
    API_BUFFER_CALLS,

    # Universe Selection
    BASE_UNIVERSE_SIZE,
    DAILY_WATCHLIST_SIZE,
    PREMARKET_SCAN_START,
    PREMARKET_SCAN_END,
    MIN_GAP_PCT,
    MIN_PREMARKET_VOLUME,
    MIN_PREMARKET_REL_VOLUME,
    MAX_FLOAT_PREFERRED,
    PRICE_MIN,
    PRICE_MAX,
    UNIVERSE_PATH,

    # Scanning
    SCAN_INTERVAL_SECONDS,
    API_CALLS_PER_STOCK,
    OPTIMAL_TRADING_START,
    OPTIMAL_TRADING_END,
    AVOID_FIRST_MINUTES,
    AVOID_LAST_MINUTES,

    # Signal Generation (NEW)
    REQUIRE_ABOVE_VWAP,
    MIN_BREAKOUT_PCT,
    MIN_RELATIVE_VOLUME,
    RSI_MIN,
    RSI_MAX,
    MIN_ENTRY_SCORE,
    SCORE_ABOVE_VWAP,
    SCORE_BREAKOUT,
    SCORE_VOLUME,
    SCORE_RSI_VALID,
    SCORE_STRONG_BREAKOUT,
    SCORE_HIGH_VOLUME,
    SCORE_RSI_SWEET,
    SCORE_LARGE_GAP,

    # Legacy scoring (kept for compatibility)
    SCORE_5MIN_BREAKOUT,
    SCORE_15MIN_GREEN,
    SCORE_2MIN_BREAKOUT,
    SCORE_VELOCITY_RATIO,
    SCORE_ACCELERATION,
    SCORE_ACCELERATION_MED,

    # Buyer Settings
    SIGNAL_MAX_AGE_SECONDS,
    MAX_SLIPPAGE_PCT,
    MAX_SPREAD_PCT,
    USE_LIMIT_ORDERS,
    LIMIT_ORDER_BUFFER,
    HOT_SIGNAL_ENABLED,
    HOT_SIGNAL_MIN_SCORE,
    HOT_CHECK_INTERVAL,

    # Position Sizing
    MAX_POSITIONS,
    POSITION_SIZE_STANDARD,
    POSITION_SIZE_STRONG,
    POSITION_SIZE_MAXIMUM,
    POSITION_SIZE_PYRAMID,
    SCORE_TIER_STANDARD,
    SCORE_TIER_STRONG,
    SCORE_TIER_MAXIMUM,

    # Risk Management
    STOP_LOSS_PCT,
    BREAKEVEN_PROFIT,
    QUICK_LOCK_PROFIT,
    TRAIL_RULE_MULTIPLIER,
    TRAILING_STOPS,
    DECEL_EXIT_THRESHOLD,
    DECEL_TIGHTEN_THRESHOLD,
    MIN_PROFIT_FOR_DECEL_CHECK,

    # Monitor Settings
    MONITOR_INTERVAL_SECONDS,
    POSITION_CHECK_INTERVAL,

    # Seller Settings
    SELLER_INTERVAL_SECONDS,

    # Cooldown
    COOLDOWN_MINUTES,

    # Re-Entry & Pyramiding
    ALLOW_PYRAMIDING,
    MIN_PROFIT_FOR_PYRAMID,
    MIN_SCORE_IMPROVEMENT,
    PYRAMID_SIZE_PCT,

    # Timeframes
    TIMEFRAME_FAST,
    TIMEFRAME_PRIMARY,
    BARS_FAST,
    BARS_PRIMARY,

    # Volatility Filters
    MIN_ATR_PCT,
    HIGH_VOLATILITY_ATR,

    # Legacy Entry Requirements
    BREAKOUT_5MIN_PCT,
    BREAKOUT_2MIN_PCT,
    VOLUME_RATIO_MIN,
    ACCELERATION_MIN,

    # Default Universe
    DEFAULT_UNIVERSE,

    # Logging
    LOG_LEVEL,
    LOG_FILE,
    LOG_FILE_DETAILED,
    LOG_TO_CONSOLE,
    CONSOLE_LOG_LEVEL,

    # API
    PAPER_TRADING,
    API_VERSION,

    # Backtesting
    BACKTEST_START_DATE,
    BACKTEST_END_DATE,
    BACKTEST_INITIAL_CAPITAL,
)

__all__ = [
    # API Rate Limits
    'API_RATE_LIMIT',
    'API_BUFFER_CALLS',

    # Universe Selection
    'BASE_UNIVERSE_SIZE',
    'DAILY_WATCHLIST_SIZE',
    'PREMARKET_SCAN_START',
    'PREMARKET_SCAN_END',
    'MIN_GAP_PCT',
    'MIN_PREMARKET_VOLUME',
    'MIN_PREMARKET_REL_VOLUME',
    'MAX_FLOAT_PREFERRED',
    'PRICE_MIN',
    'PRICE_MAX',
    'UNIVERSE_PATH',

    # Scanning
    'SCAN_INTERVAL_SECONDS',
    'API_CALLS_PER_STOCK',
    'OPTIMAL_TRADING_START',
    'OPTIMAL_TRADING_END',
    'AVOID_FIRST_MINUTES',
    'AVOID_LAST_MINUTES',

    # Signal Generation
    'REQUIRE_ABOVE_VWAP',
    'MIN_BREAKOUT_PCT',
    'MIN_RELATIVE_VOLUME',
    'RSI_MIN',
    'RSI_MAX',
    'MIN_ENTRY_SCORE',
    'SCORE_ABOVE_VWAP',
    'SCORE_BREAKOUT',
    'SCORE_VOLUME',
    'SCORE_RSI_VALID',
    'SCORE_STRONG_BREAKOUT',
    'SCORE_HIGH_VOLUME',
    'SCORE_RSI_SWEET',
    'SCORE_LARGE_GAP',

    # Legacy scoring
    'SCORE_5MIN_BREAKOUT',
    'SCORE_15MIN_GREEN',
    'SCORE_2MIN_BREAKOUT',
    'SCORE_VELOCITY_RATIO',
    'SCORE_ACCELERATION',
    'SCORE_ACCELERATION_MED',

    # Buyer Settings
    'SIGNAL_MAX_AGE_SECONDS',
    'MAX_SLIPPAGE_PCT',
    'MAX_SPREAD_PCT',
    'USE_LIMIT_ORDERS',
    'LIMIT_ORDER_BUFFER',
    'HOT_SIGNAL_ENABLED',
    'HOT_SIGNAL_MIN_SCORE',
    'HOT_CHECK_INTERVAL',

    # Position Sizing
    'MAX_POSITIONS',
    'POSITION_SIZE_STANDARD',
    'POSITION_SIZE_STRONG',
    'POSITION_SIZE_MAXIMUM',
    'POSITION_SIZE_PYRAMID',
    'SCORE_TIER_STANDARD',
    'SCORE_TIER_STRONG',
    'SCORE_TIER_MAXIMUM',

    # Risk Management
    'STOP_LOSS_PCT',
    'BREAKEVEN_PROFIT',
    'QUICK_LOCK_PROFIT',
    'TRAIL_RULE_MULTIPLIER',
    'TRAILING_STOPS',
    'DECEL_EXIT_THRESHOLD',
    'DECEL_TIGHTEN_THRESHOLD',
    'MIN_PROFIT_FOR_DECEL_CHECK',

    # Monitor Settings
    'MONITOR_INTERVAL_SECONDS',
    'POSITION_CHECK_INTERVAL',

    # Seller Settings
    'SELLER_INTERVAL_SECONDS',

    # Cooldown
    'COOLDOWN_MINUTES',

    # Re-Entry & Pyramiding
    'ALLOW_PYRAMIDING',
    'MIN_PROFIT_FOR_PYRAMID',
    'MIN_SCORE_IMPROVEMENT',
    'PYRAMID_SIZE_PCT',

    # Timeframes
    'TIMEFRAME_FAST',
    'TIMEFRAME_PRIMARY',
    'BARS_FAST',
    'BARS_PRIMARY',

    # Volatility Filters
    'MIN_ATR_PCT',
    'HIGH_VOLATILITY_ATR',

    # Legacy Entry Requirements
    'BREAKOUT_5MIN_PCT',
    'BREAKOUT_2MIN_PCT',
    'VOLUME_RATIO_MIN',
    'ACCELERATION_MIN',

    # Default Universe
    'DEFAULT_UNIVERSE',

    # Logging
    'LOG_LEVEL',
    'LOG_FILE',
    'LOG_FILE_DETAILED',
    'LOG_TO_CONSOLE',
    'CONSOLE_LOG_LEVEL',

    # API
    'PAPER_TRADING',
    'API_VERSION',

    # Backtesting
    'BACKTEST_START_DATE',
    'BACKTEST_END_DATE',
    'BACKTEST_INITIAL_CAPITAL',
]
